#### Config file for FASTQ/BAM files ####
# Edit the following parameters below: #

# specify list of sample names
sample_list: "../manifests/fastq_example_sample_file.txt"

# specify list of patient id's
patient_list: "../manifests/fastq_example_patient_ids.txt"

#specify key that links sample names and patient id's
patient_key: "../manifests/fastq_example_key.tsv"

#reference transcriptome
transcriptome: "../references/refdata-gex-GRCh38-2020-A"

#cellranger path
cellranger: "/home/administrator/cellranger-9.0.1/bin/cellranger"
