#### Config file for MTX files ####

# Note: Seeds for each run are adjustable in the handle_mtx.snake file 

# Edit the following parameters below to match your filenames #

# specify list of sample names
sample_list: "../manifests/matrix_example_sample_file.txt"

# specify list of patient id's
patient_list: "../manifests/matrix_example_patient_ids.txt"

#specify key that links sample names and patient id's
patient_key: "../manifests/matrix_example_key.tsv"

#reference transcriptome
transcriptome: "../references/refdata-gex-GRCh38-2024-A"

#cellranger path
cellranger: "/home/administrator/cellranger-7.2.0/bin/cellranger"

# Threshold cut-off for MSI status 
msi_cutoff: 0.75
